from models.class_models import StepDefinition


WORKFLOW_PROCESSORS = [
    "extract_metadata",
    "template_mapping",
    "parse_file_to_json",
    "publish_data",
    "template_validation",
    "write_json_to_s3",
    # === Masterdata only ===
    "master_validation",
    "master_sync_data",
    "write_raw_to_s3",
    # === Rule mapping only ===
    "rule_mapping_submit",
    "rule_mapping_xsl_translation",
    "rule_mapping_metadata_extract",
    "rule_mapping_send_to",
    "rule_mapping_rename",
]

PROCESS_DEFINITIONS = {
    "TEMPLATE_FILE_PARSE": StepDefinition(
        function_name="parse_file_to_json",
        data_input=None,
        data_output="parsed_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},

    ),
    "TEMPLATE_FORMAT_VALIDATION": StepDefinition(
        function_name="template_format_validation",
        data_input="parsed_data",
        data_output="validation_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "TEMPLATE_DATA_MAPPING": StepDefinition(
        function_name="template_data_mapping",
        data_input="parsed_data",
        data_output="mapped_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "TEMPLATE_PUBLISH_DATA": StepDefinition(
        function_name="publish_data",
        data_input="mapped_data",
        data_output="publish_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={"connectionDto": None},
        extract_to={},
    ),
    # === Masterdata only ===
    "MASTER_DATA_FILE_PARSER": StepDefinition(
        function_name="parse_file_to_json",
        data_input=None,
        data_output="master_parsed_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "MASTER_DATA_VALIDATE_HEADER": StepDefinition(
        function_name="masterdata_header_validation",
        data_input="master_parsed_data",
        data_output="master_header_validation",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "MASTER_DATA_VALIDATE_DATA": StepDefinition(
        function_name="masterdata_data_validation",
        data_input="master_parsed_data",
        data_output="master_data_validation",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "MASTER_DATA_LOAD_DATA": StepDefinition(
        function_name="master_sync_data",
        data_input="master_data_validation",
        data_output="master_sync_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={"customized_object_name": True},
        extract_to={},
    ),
    # === Rule mapping only ===
    "[RULE_MP]_SUBMIT" : StepDefinition(
        function_name = "submit",
        data_input="mapped_data",
        data_output="submit_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "[RULE_MP]_XSL_TRANSLATION" : StepDefinition(
        function_name = "xsl_translation",
        data_input="mapped_data",
        data_output="xsl_translation_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "[RULE_MP]_METADATA_EXTRACT" : StepDefinition(
        function_name = "metadata_extract",
        data_input="mapped_data",
        data_output="metadata_extract",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "[RULE_MP]_SEND_TO" : StepDefinition(
        function_name = "send_to",
        data_input="mapped_data",
        data_output="send_to",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
    "[RULE_MP]_RENAME" : StepDefinition(
        function_name = "rename",
        data_input="mapped_data",
        data_output="rename_data",
        require_data_api = True,
        require_data_output=True,
        target_store_data="workflow-node-materialized",
        args=[],
        kwargs={},
        extract_to={},
    ),
}

BUCKET_MAP = {
    "raw_bucket": {
        "DKSH_TW": "datahub_s3_raw_data_tw",
        "DKSH_VN": "datahub_s3_raw_data_vn",
    },
    "target_bucket": {
        "order": {
            "DKSH_TW": "datahub_s3_process_data_tw",
            "DKSH_VN": "datahub_s3_process_data_vn",
        },
        "master_data": {
            "sap_masterdata": "sap_masterdata_bucket",
            "DKSH_TW": "tw_masterdata_bucket",
            "DKSH_VN": "vn_masterdata_bucket",
        },
    },
}